package com.mychao.emark.entity;

import java.util.Date;

public class EmarkCategoryPropertiesEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.category_size
     *
     * @mbggenerated
     */
    private String categorySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.category_price
     *
     * @mbggenerated
     */
    private Long categoryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_category_properties.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.id
     *
     * @return the value of emark_category_properties.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.id
     *
     * @param id the value for emark_category_properties.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.category_id
     *
     * @return the value of emark_category_properties.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.category_id
     *
     * @param categoryId the value for emark_category_properties.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.category_size
     *
     * @return the value of emark_category_properties.category_size
     *
     * @mbggenerated
     */
    public String getCategorySize() {
        return categorySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.category_size
     *
     * @param categorySize the value for emark_category_properties.category_size
     *
     * @mbggenerated
     */
    public void setCategorySize(String categorySize) {
        this.categorySize = categorySize == null ? null : categorySize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.category_price
     *
     * @return the value of emark_category_properties.category_price
     *
     * @mbggenerated
     */
    public Long getCategoryPrice() {
        return categoryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.category_price
     *
     * @param categoryPrice the value for emark_category_properties.category_price
     *
     * @mbggenerated
     */
    public void setCategoryPrice(Long categoryPrice) {
        this.categoryPrice = categoryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.create_time
     *
     * @return the value of emark_category_properties.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.create_time
     *
     * @param createTime the value for emark_category_properties.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_category_properties.update_time
     *
     * @return the value of emark_category_properties.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_category_properties.update_time
     *
     * @param updateTime the value for emark_category_properties.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}