package com.mychao.emark.entity;

import java.util.Date;

public class EmarkUserCompanyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.user_acount_id
     *
     * @mbggenerated
     */
    private Long userAcountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_address
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_contract_user
     *
     * @mbggenerated
     */
    private String companyContractUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_contract_method
     *
     * @mbggenerated
     */
    private String companyContractMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_email
     *
     * @mbggenerated
     */
    private String companyEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.company_delivery_address
     *
     * @mbggenerated
     */
    private String companyDeliveryAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emark_user_company.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.id
     *
     * @return the value of emark_user_company.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.id
     *
     * @param id the value for emark_user_company.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.user_acount_id
     *
     * @return the value of emark_user_company.user_acount_id
     *
     * @mbggenerated
     */
    public Long getUserAcountId() {
        return userAcountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.user_acount_id
     *
     * @param userAcountId the value for emark_user_company.user_acount_id
     *
     * @mbggenerated
     */
    public void setUserAcountId(Long userAcountId) {
        this.userAcountId = userAcountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_name
     *
     * @return the value of emark_user_company.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_name
     *
     * @param companyName the value for emark_user_company.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_address
     *
     * @return the value of emark_user_company.company_address
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_address
     *
     * @param companyAddress the value for emark_user_company.company_address
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_contract_user
     *
     * @return the value of emark_user_company.company_contract_user
     *
     * @mbggenerated
     */
    public String getCompanyContractUser() {
        return companyContractUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_contract_user
     *
     * @param companyContractUser the value for emark_user_company.company_contract_user
     *
     * @mbggenerated
     */
    public void setCompanyContractUser(String companyContractUser) {
        this.companyContractUser = companyContractUser == null ? null : companyContractUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_contract_method
     *
     * @return the value of emark_user_company.company_contract_method
     *
     * @mbggenerated
     */
    public String getCompanyContractMethod() {
        return companyContractMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_contract_method
     *
     * @param companyContractMethod the value for emark_user_company.company_contract_method
     *
     * @mbggenerated
     */
    public void setCompanyContractMethod(String companyContractMethod) {
        this.companyContractMethod = companyContractMethod == null ? null : companyContractMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_email
     *
     * @return the value of emark_user_company.company_email
     *
     * @mbggenerated
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_email
     *
     * @param companyEmail the value for emark_user_company.company_email
     *
     * @mbggenerated
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail == null ? null : companyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.company_delivery_address
     *
     * @return the value of emark_user_company.company_delivery_address
     *
     * @mbggenerated
     */
    public String getCompanyDeliveryAddress() {
        return companyDeliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.company_delivery_address
     *
     * @param companyDeliveryAddress the value for emark_user_company.company_delivery_address
     *
     * @mbggenerated
     */
    public void setCompanyDeliveryAddress(String companyDeliveryAddress) {
        this.companyDeliveryAddress = companyDeliveryAddress == null ? null : companyDeliveryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.create_time
     *
     * @return the value of emark_user_company.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.create_time
     *
     * @param createTime the value for emark_user_company.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emark_user_company.update_time
     *
     * @return the value of emark_user_company.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emark_user_company.update_time
     *
     * @param updateTime the value for emark_user_company.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}