package com.mychao.emark.repository.mapper;

import com.mychao.emark.entity.EmarkUserAccountEntity;

public interface EmarkUserAccountEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    int insert(EmarkUserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    int insertSelective(EmarkUserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    EmarkUserAccountEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmarkUserAccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmarkUserAccountEntity record);
}