package com.mychao.emark.repository.mapper;

import com.mychao.emark.entity.EmarkCategoryPropertiesEntity;

public interface EmarkCategoryPropertiesEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    int insert(EmarkCategoryPropertiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    int insertSelective(EmarkCategoryPropertiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    EmarkCategoryPropertiesEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmarkCategoryPropertiesEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_category_properties
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmarkCategoryPropertiesEntity record);
}