package com.mychao.emark.repository.mapper;

import com.mychao.emark.entity.EmarkUserCompanyEntity;

public interface EmarkUserCompanyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    int insert(EmarkUserCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    int insertSelective(EmarkUserCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    EmarkUserCompanyEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmarkUserCompanyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_user_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmarkUserCompanyEntity record);
}