package com.mychao.emark.repository.mapper;

import com.mychao.emark.entity.EmarkOrderEntity;

public interface EmarkOrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    int insert(EmarkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    int insertSelective(EmarkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    EmarkOrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmarkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmarkOrderEntity record);
}