package com.mychao.emark.repository.mapper;

import com.mychao.emark.entity.EmarkOrderDetailEntity;

public interface EmarkOrderDetailEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    int insert(EmarkOrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(EmarkOrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    EmarkOrderDetailEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmarkOrderDetailEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emark_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmarkOrderDetailEntity record);
}